### ISSUE TITLE
同组见证人的对端IP地址不更新

### ISSUE THREAD

**Issue by wjdfx** [nerthus-foundation-ltd/nerthus#1]
某一些验证人里的A验证人在成功启动了见证服务后，切换了IP地址，其他的见证人执行：
web3.currentProvider.send({jsonrpc: '2.0',  id: 1,  method: 'witness_getWitnessGroupList',   params: [] },
function(r1,response){  console.log(JSON.stringify(response,null,2)) })
得到的A验证人的IP地址还是切换前的，但A验证人旧的运行见证服务的已经关停。造成：
其它的验证人一直无法与A验证人进行通讯。

问题并不会100%复现，A验证人的服务器目前处于可追溯状态。

**Comment by ysqi** [comment]
@wjdfx 很抱歉，之前尚未留意到你的提问。这个问题在v0.6.16版本中已经解决。
