### ISSUE TITLE
env.sh 文件问题

### ISSUE THREAD

**Issue by mode6** [nerthus-foundation-ltd/nerthus#2]
ip="183.14.133.98"
workspace="/datadisk/nerthus"
password="mypassword"
witness="nts17r3mt25ermntzwwl8t6eflaej0v2h0ctkn5094"
这个是示例，在初始化后，ip 地址就消失了。需要手工填写。

**Comment by ysqi** [comment]
这个设计之初是假定不会重复初始化。一次初始化后便不需要再次修改。如果需要重新初始化则需要填写。

因此，我先关闭此 Issue，如果你觉得有疑问，我们再讨论。

**Comment by mode6** [comment]
我手工修改了下配置。好了


------------------








------------------ 原始邮件 ------------------
发件人: "YuShuangqi"<notifications@github.com>;
发送时间: 2019年9月16日(星期一) 上午10:22
收件人: "nerthus-foundation-ltd/nerthus"<nerthus@noreply.github.com>;
抄送: "冰红茶"<2779476373@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [nerthus-foundation-ltd/nerthus] env.sh 文件问题 (#2)




这个设计之初是假定不会重复初始化。一次初始化后便不需要再次修改。如果需要重新初始化则需要填写。
 
因此，我先关闭此 Issue，如果你觉得有疑问，我们再讨论。
