### ISSUE TITLE
这个安装说明格式化硬盘后没有更新fstab 重启后分区消失，建议加上。

### ISSUE THREAD

**Issue by mode6** [nerthus-foundation-ltd/nerthus#3]
https://dochub.nerthusfoundation.io/start/witness_start.html

newdisk="你的数据盘名称" # disk name
mountdir="/datadisk" # dictionary

(
echo o # Create a new empty DOS partition table
echo n # Add a new partition
echo p # Primary partition
echo 1 # Partition number
echo   # First sector (Accept default: 1)
echo   # Last sector (Accept default: varies)
echo w # Write changes
) | fdisk $newdisk

partprobe
mkfs -t ext4 $newdisk
mkdir -p $mountdir
mount $newdisk $mountdir
df -TH

**Comment by ysqi** [comment]
请问你是在哪个版本的 Linux下操作的？

**Comment by mode6** [comment]
centos 7


------------------



冰红茶
大矿工
迅雷大矿机运营管理


 联系我









 




------------------ 原始邮件 ------------------
发件人: "YuShuangqi"<notifications@github.com>;
发送时间: 2019年9月16日(星期一) 上午10:19
收件人: "nerthus-foundation-ltd/nerthus"<nerthus@noreply.github.com>;
抄送: "冰红茶"<2779476373@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [nerthus-foundation-ltd/nerthus] 这个安装说明格式化硬盘后没有更新fstab 重启后分区消失，建议加上。 (#3)




请问你是在哪个版本的 Linux下操作的？
