### ISSUE TITLE
优化：调整新合约的初始见证人和合约创建人的见证人一致

### ISSUE THREAD

**Issue by ysqi** [nerthus-foundation-ltd/nerthus#4]
每次部署新合约时将需要给合约分配见证人。当时是进行一次随机分配，但这样做是不需要的。可以降低执行开销，直接将合约分配到和合约创建者一样的见证组即可。

这样的好处有两点：
1.  合约可以立即得到初始化。因为发送部署合约的交易能够被处理，则说明合约创建者的见证人当前是积极工作的。
2. 可以提高合约创建者的积极性，积极处理部署新合约的交易。

**Comment by xiaogan18** [comment]
已优化，将在新版本中体现
