### ISSUE TITLE
本地存储需要保留已过期的本地交易

### ISSUE THREAD

**Issue by ysqi** [nerthus-foundation-ltd/nerthus#5]
交易默认是有过期是的，当交易迟迟未能处理将会在交易池中移除。这样会导致用户创建的交易会莫名其妙的小时，这会使得用户感到疑惑。

因此，如果交易时来自本地交易，则即使过期也需要永久存储。
在钱包上，用户看到的交易状态将显示为过期。

**Comment by xiaogan18** [comment]
已优化
