### ISSUE TITLE
新节点同步数据时，出现bad unit

### ISSUE THREAD

**Issue by xiaogan18** [nerthus-foundation-ltd/nerthus#6]
### 现象
- 启动一个新节点同步链数据时，出现bad unit导致同步无法继续。
### 分析
- 同步数据时，见证人工作量统计不正确。
- 见证人提现交易计算使用不正确的统计数据，单元执行结果state root偏差，误判为bad unit。
- 节点发现bad unit会断开与相关节点的连接，同步无法继续。
### 可能原因
- 同步时没有按时间线顺序依次同步单元。
- 工作量统计出现错误。

**Comment by Samjii** [comment]
如果旧节点，删除全部数据后重新同步，同步到某个点时无法继续同步的话，该怎么解决？

我的旧节点出现过无法继续同步情况，全部删除数据后，上传钱包数据后仍然无法同步，现在只能是从头开始，这次升级前是完全可以用其他节点或者钱包数据的。

**Comment by xiaogan18** [comment]
@Samjii  确认一下是否同一个问题，目前正在积极解决，耐心等待新版本

**Comment by Samjii** [comment]
从0开始同步数据到height: 20232就报错无法继续了！

-- Logs begin at 一 2019-09-16 13:27:06 CST. --
9月 17 07:04:04 localhost.localdomain witness_cli.sh[78744]: {
9月 17 07:04:04 localhost.localdomain witness_cli.sh[78744]: "To": "nts1majd0pqgpsv92aj7ydxv2ll0xg3k7y0qc05lzt",
9月 17 07:04:04 localhost.localdomain witness_cli.sh[78744]: "Amount": "0x15d0f522d5b516"
9月 17 07:04:04 localhost.localdomain witness_cli.sh[78744]: }
9月 17 07:04:04 localhost.localdomain witness_cli.sh[78744]: ],
9月 17 07:04:04 localhost.localdomain witness_cli.sh[78744]: "output": "0x"
9月 17 07:04:04 localhost.localdomain witness_cli.sh[78744]: }
9月 17 07:04:04 localhost.localdomain witness_cli.sh[78744]: ]
9月 17 07:04:04 localhost.localdomain witness_cli.sh[78744]: ============
9月 17 07:04:04 localhost.localdomain witness_cli.sh[78744]: WARN [09-17|07:04:04] found bad unit                           unitInfo="\n########## BAD UNIT #########\nChain: 1907\nError: invalid state merkle root hash(remote: 724f22a574411be56391b6a480e529634d334f46796859afd1dc468b92ab94b2 local: 9519cfb6c9286ed056380e8f45f5a0b204eb281f0d17d609e5f180020e5e1bd2)\nUnitHash: 0x9b643d30810c7fe8be0ab4b78d17f60899812efd784c1e790614136473708b2c\nUnit:\n\t{\n\t\"header\": {\n\t\t\"mc\": \"nsc1qyqszq0xz2kr7hnwqujwa6z97m382vysnt75v3\",\n\t\t\"number\": \"0x4f09\",\n\t\t\"parent_hash\": \"0xa7ac2fb9ff20f537c131c9f33c30660c0f7a0c0f6f107d972ff7a6fcbb5decbc\",\n\t\t\"sc_hash\": \"0xa7ac2fb9ff20f537c131c9f33c30660c0f7a0c0f6f107d972ff7a6fcbb5decbc\",\n\t\t\"sc_number\": \"0x4f08\",\n\t\t\"proposer\": \"nts1rxl8mg5h7j0td5x8fkzayfthxw7e6nm7dqj0wj\",\n\t\t\"transactions_root\": \"0xd190fa5d97d589a3bb0a2704e9b3ed249575b78fee070c6a3b23a274fabccb7f\",\n\t\t\"receipt_root\": \"0xa908e9c5e40f6c36a21bb41edf8fbf42f17f1a43beeb1637492fdb8c4b235a9c\",\n\t\t\"state_root\": \"0x724f22a574411be56391b6a480e529634d334f46796859afd1dc468b92ab94b2\",\n\t\t\"bloom\": \"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\",\n\t\t\"gas_limit\": \"0x989680\",\n\t\t\"gas_used\": \"0x3ff37c\",\n\t\t\"timestamp\": \"0x15b3698e2251bfdc\",\n\t\t\"hash\": \"0x9b643d30810c7fe8be0ab4b78d17f60899812efd784c1e790614136473708b2c\"\n\t},\n\t\"transactions\": [\n\t\t{\n\t\t\t\"action\": \"sc_idle_contract_deal\",\n\t\t\t\"prestep\": {\n\t\t\t\t\"chain_id\": \"nts100000000000000000000000000000000000000\",\n\t\t\t\t\"height\": 0,\n\t\t\t\t\"hash\": \"0x0000000000000000000000000000000000000000000000000000000000000000\"\n\t\t\t},\n\t\t\t\"tx_hash\": \"0x8827d97331489e7fee604add2bbc26f42caac6804d2396674fbd9113d6ad34c5\",\n\t\t\t\"tx\": {\n\t\t\t\t\"time\": \"0x15b369793243847e\",\n\t\t\t\t\"gasPrice\": \"0x0\",\n\t\t\t\t\"gas\": \"0x0\",\n\t\t\t\t\"sender\": \"nts1rxl8mg5h7j0td5x8fkzayfthxw7e6nm7dqj0wj\",\n\t\t\t\t\"to\": \"nsc1qyqszq0xz2kr7hnwqujwa6z97m382vysnt75v3\",\n\t\t\t\t\"value\": \"0x0\",\n\t\t\t\t\"input\": \"0x6bb43e01\",\n\t\t\t\t\"seed\": \"0x0\",\n\t\t\t\t\"timeout\": \"0x1356\",\n\t\t\t\t\"sign\": \"f82acjvfWJZg4qrSCZ+43mhCsUFjchu/50tiTGoPC8Qqd0kutrKbYhfXUeu0v3ksGk8yjiMk47DBLBTZf3bV8A8J\",\n\t\t\t\t\"hash\": \"0x8827d97331489e7fee604add2bbc26f42caac6804d2396674fbd9113d6ad34c5\",\n\t\t\t\t\"from\": \"nts1rxl8mg5h7j0td5x8fkzayfthxw7e6nm7dqj0wj\"\n\t\t\t},\n\t\t\t\"hash\": \"0x61e3d9045fe1430ff75c73bf0f454a81856674becc19303193aeba665f35f4c4\"\n\t\t},\n\t\t{\n\t\t\t\"action\": \"sc_idle_contract_deal\",\n\t\t\t\"prestep\": {\n\t\t\t\t\"chain_id\": \"nts100000000000000000000000000000000000000\",\n\t\t\t\t\"height\": 0,\n\t\t\t\t\"hash\": \"0x0000000000000000000000000000000000000000000000000000000000000000\"\n\t\t\t},\n\t\t\t\"tx_hash\": \"0x44940683a3cebf41330fcc68bce0a4fcbbf36e6df3be524e1a26bca651d29e95\",\n\t\t\t\"tx\": {\n\t\t\t\t\"time\": \"0x15b3696031633778\",\n\t\t\t\t\"gasPrice\": \"0x0\",\n\t\t\t\t\"gas\": \"0x0\",\n\t\t\t\t\"sender\": \"nts1fvqywg7rzw32x79vvlx9fa7jvhyspy05zdnsww\",\n\t\t\t\t\"to\": \"nsc1qyqszq0xz2kr7hnwqujwa6z97m382vysnt75v3\",\n\t\t\t\t\"value\": \"0x0\",\n\t\t\t\t\"input\": \"0x6bb43e01\",\n\t\t\t\t\"seed\": \"0x0\",\n\t\t\t\t\"timeout\": \"0x3de\",\n\t\t\t\t\"sign\": \"JuWEdG6inHtCFHoldyllGjCvnOJAh2cWYjwTBb52Acgeq6Pndv1kmAbNj1cuxHOX404uWcR5SO6yZo52JqiXAA8K\",\n\t\t\t\t\"hash\": \"0x44940683a3cebf41330fcc68bce0a4fcbbf36e6df3be524e1a26bca651d29e95\",\n\t\t\t\t\"from\": \"nts1fvqywg7rzw32x79vvlx9fa7jvhyspy05zdnsww\"\n\t\t\t},\n\t\t\t\"hash\": \"0x658343c0ae76c73b872e8a2d1b864b974bc2f87bdf43c98e8a5b5d61b66f0f74\"\n\t\t},\n\t\t{\n\t\t\t\"action\": \"sc_idle_contract_deal\",\n\t\t\t\"prestep\": {\n\t\t\t\t\"chain_id\": \"nts100000000000000000000000000000000000000\",\n\t\t\t\t\"height\": 0,\n\t\t\t\t\"hash\": \"0x0000000000000000000000000000000000000000000000000000000000000000\"\n\t\t\t},\n\t\t\t\"tx_hash\": \"0xcc9566ea178abea698682901bde4caf6a8f08ac5ce92d780507eb6f06750e6a0\",\n\t\t\t\"tx\": {\n\t\t\t\t\"time\": \"0x15b369676829e511\",\n\t\t\t\t\"gasPrice\": \"0x0\",\n\t\t\t\t\"gas\": \"0x0\",\n\t\t\t\t\"sender\": \"nts1czgege3h2af379007xekl5xam7ll2d80fql6q4\",\n\t\t\t\t\"to\": \"nsc1qyqszq0xz2kr7hnwqujwa6z97m382vysnt75v3\",\n\t\t\t\t\"value\": \"0x0\",\n\t\t\t\t\"input\": \"0x6bb43e01\",\n\t\t\t\t\"seed\": \"0x0\",\n\t\t\t\t\"timeout\": \"0x3de\",\n\t\t\t\t\"sign\": \"MOpFxE8pCOtfNmQB6L+hKfsI6ScyvzyO7F8V5TfWhzINsYTVtNGyUsh69aWUuOMObF9HGtOZ9J9o5EH6bvrWHQ8J\",\n\t\t\t\t\"hash\": \"0xcc9566ea178abea698682901bde4caf6a8f08ac5ce92d780507eb6f06750e6a0\",\n\t\t\t\t\"from\": \"nts1czgege3h2af379007xekl5xam7ll2d80fql6q4\"\n\t\t\t},\n\t\t\t\"hash\": \"0x95ce28f47a95824928da702e56d410a9cfb57f7fcd11445dcb6f332918474c63\"\n\t\t},\n\t\t{\n\t\t\t\"action\": \"sc_idle_contract_deal\",\n\t\t\t\"prestep\": {\n\t\t\t\t\"chain_id\": \"nts100000000000000000000000000000000000000\",\n\t\t\t\t\"height\": 0,\n\t\t\t\t\"hash\": \"0x0000000000000000000000000000000000000000000000000000000000000000\"\n\t\t\t},\n\t\t\t\"tx_hash\": \"0x019f7edbfccc41567c4558cf6b2a9dfa459879766b0b1eca94881799dab116bb\",\n\t\t\t\"tx\": {\n\t\t\t\t\"time\": \"0x15b369601a2599e2\",\n\t\t\t\t\"gasPrice\": \"0x0\",\n\t\t\t\t\"gas\": \"0x0\",\n\t\t\t\t\"sender\": \"nts10gu85vm93emhvkqy06ep6aqet5atja7zysnc96\",\n\t\t\t\t\"to\": \"nsc1qyqszq0xz2kr7hnwqujwa6z97m382vysnt75v3\",\n\t\t\t\t\"value\": \"0x0\",\n\t\t\t\t\"input\": \"0x6bb43e01\",\n\t\t\t\t\"seed\": \"0x0\",\n\t\t\t\t\"timeout\": \"0x3de\",\n\t\t\t\t\"sign\": \"5x+yAsldfe+EEkHWoRW888brYy3vYbb20JvB1TzqEVo8bDwq5Amd9vO6QQLG4XITblk38A5Jj0QEwQGib4vVVA8K\",\n\t\t\t\t\"hash\": \"0x019f7edbfccc41567c4558cf6b2a9dfa459879766b0b1eca94881799dab116bb\",\n\t\t\t\t\"from\": \"nts10gu85vm93emhvkqy06ep6aqet5atja7zysnc96\"\n\t\t\t},\n\t\t\t\"hash\": \"0xa1c5fb4589e60f07bbd666030372f3ab9282c431264f7c40f8530b663c1733bf\"\n\t\t},\n\t\t{\n\t\t\t\"action\": \"contract_deal\",\n\t\t\t\"prestep\": {\n\t\t\t\t\"chain_id\": \"nts1majd0pqgpsv92aj7ydxv2ll0xg3k7y0qc05lzt\",\n\t\t\t\t\"height\": 16,\n\t\t\t\t\"hash\": \"0x024ab49e6047096eea00be8581693f8102a9c1793fc8bb9436a07c0103a165cb\"\n\t\t\t},\n\t\t\t\"tx_hash\": \"0x05c361aa9d75491a3aab88a2bf6d29c72a57d5ed0c7ba135265f33458003312f\",\n\t\t\t\"tx\": null,\n\t\t\t\"hash\": \"0xa95bd1bbc77fb07b38690eb825dae33bd64a48a5af86eb80266179d2b2b8a407\"\n\t\t}\n\t],\n\t\"witness_sign\": [\n\t\t{\n\t\t\t\"extra\": \"AwAAAAAAAAAA\",\n\t\t\t\"sign\": \"RX4FEQ56Jsa5SZ6OGQ8q4W9i9jkttlEd/Tn/6sx2UQ8eJaVSeayHJwlscKHXIJR2xaBLIgFnMcoV45Smu7iKEw8K\"\n\t\t},\n\t\t{\n\t\t\t\"extra\": \"AwAAAAAAAAAA\",\n\t\t\t\"sign\": \"+ZzENIetJ5x6e2s77ALuy/zUUZ+o6Z4jISyBN/gs9lJUR9D5/5YlOKx+tYaiB0t++Pbt/ZtdvSs9b025lIOa+Q8K\"\n\t\t},\n\t\t{\n\t\t\t\"extra\": \"AwAAAAAAAAAA\",\n\t\t\t\"sign\": \"OOC2x3xZDijK5/Fi9IEbqs41m+Iw8P3YNSYsVHQdiegSA56EqCNUGgAuzgsC2wPBAAxUcDzm/OLy/1rXvvRuEA8J\"\n\t\t},\n\t\t{\n\t\t\t\"extra\": \"AwAAAAAAAAAA\",\n\t\t\t\"sign\": \"JYU9xcbTCe9zNdXMBw8KtKWKfmsXgUN3hd0YweKtM157FDKiZj6UdNKipuz+sFjHjtiLTukm6MGDNAtU7rJGzw8K\"\n\t\t},\n\t\t{\n\t\t\t\"extra\": \"AwAAAAAAAAAA\",\n\t\t\t\"sign\": \"mXEbb6usX+gZrJLdfWPH70WhX/b+jPFlKKvAW/cvNAgXkUaxhnwfSfWW3BbZ7YLceAPdOVcvTFFHJKUt6RZsQA8J\"\n\t\t},\n\t\t{\n\t\t\t\"extra\": \"AwAAAAAAAAAA\",\n\t\t\t\"sign\": \"e1ac4gasS4lQZImTEaeB8arIRhdXKS5SO1m928NCXosf+OcC3OU3wB5CCqvLvN/Waa/Hc5C4cbpIfOU7l3FYHg8J\"\n\t\t},\n\t\t{\n\t\t\t\"extra\": \"AwAAAAAAAAAA\",\n\t\t\t\"sign\": \"WiD9X71G0O17M0JW6613PjOu9sb3auvd6GIDN4cXYAdRskSpKWSwnVVZPEmvQdkW+hWsPrzEUb4mm5RxpNPIUQ8K\"\n\t\t},\n\t\t{\n\t\t\t\"extra\": \"AwAAAAAAAAAA\",\n\t\t\t\"sign\": \"ZzVJHx88sFnVPq4eYkuSp6JuBs70roLcUiW5pfxMEpIyCP2kwynEQ70pXdhfc281B5gV6ni0S4Ta6LDuJMkPpw8J\"\n\t\t}\n\t],\n\t\"witnesses\": [\n\t\t\"nts1wyh2ats9zqd2uuh4pg9ws700hx4eqelrxmdkfp\",\n\t\t\"nts1x9q04v24hxxlw058pry60lttgxm09fgeamfxzy\",\n\t\t\"nts17jxh9sq3pp4un8tz2czyrgxtqxdjtkmaq7sds4\",\n\t\t\"nts1ukw85sf6ys9j20r8ny6vks8fk7cl70cjsnu6ke\",\n\t\t\"nts1g46wmnnlstauh45vlkdetcld5y50pj8vz97a5z\",\n\t\t\"nts1d69vtxt20rt9k8yue8c8fc07s45v7njm5ga8uw\",\n\t\t\"nts1rxl8mg5h7j0td5x8fkzayfthxw7e6nm7dqj0wj\",\n\t\t\"nts13p9a9rdyk97c2ma9rq6cegcw449hcg3qxa8cmv\"\n\t],\n\t\"sign\": \"T/092zCtPLIFlhIOeYz0bU+eyJe5lWb8zhgFVtYJiqgJYnF3//KDnPaCV5pmNkYMPB3vP9kvGlkhXrcPEczRkA8K\"\n}\n##############################\n"

**Comment by xiaogan18** [comment]
已在新版本中修复
